### ISSUE TITLE
FlutterWeb-Pizza is not working

### ISSUE THREAD

**Issue by jegathispandian** [JideGuru/FlutterWeb-Pizza#3]
![Screen Shot 2019-06-21 at 9 32 25 AM](https://user-images.githubusercontent.com/22149849/59896789-8ba46700-9407-11e9-9c9a-277975140334.png)

**Comment by Levi-Lesches** [comment]
Just put that function call as the first line in `main`

**Comment by Levi-Lesches** [comment]
It's from `dart:ui`

**Comment by jegathispandian** [comment]
Have you fixed and commit your latest code?

**Comment by Levi-Lesches** [comment]
There you go. Just merge that and you'll be done. But it's not **my** code, you really should have done it.

**Comment by jegathispandian** [comment]
![Screen Shot 2019-06-25 at 9 50 44 AM](https://user-images.githubusercontent.com/22149849/60068983-bb68ad00-972e-11e9-98c4-16cc68fde889.png)

I have merged the code. Still, I am facing this issue. could you please look into it

**Comment by Levi-Lesches** [comment]
It's not merged yet (at least not on GitHub)

**Comment by JideGuru** [comment]
I have merged the pull request. i hope that solves the issue.
