### ISSUE TITLE
can‘t run 

### ISSUE THREAD

**Issue by jeffinzhang** [JideGuru/FlutterWeb-Pizza#5]
hello I just download your project ,then input “flutter run -d chrome” order. The following error is indicated
![image](https://user-images.githubusercontent.com/18242297/92548026-948d8c80-f288-11ea-99f0-44fd48dcf699.png)

**Comment by Levi-Lesches** [comment]
Not my project, I kinda just found this once but it's running an older version of Flutter. You'll need to replace the `main` function in `lib/main.dart` with the following: 

```dart 
void main() async {
  await ui.webOnlyInitializePlatform();
  runApp(MyApp());
}
```

The only thing that changed was adding an `async` after `main` and `await` before `ui.webOnlyInitializePlatform();`. This makes sure Flutter waits for that function to be called before launching the app.

**Comment by Levi-Lesches** [comment]
I submitted a PR, so if that gets approved, then this should be fixed and the issue can be closed
